app/home/__init__.py
from .views import *

app/home/views.py
from flask import render_template, Blueprint, request

home = Blueprint("home", __name__,
                 template_folder="templates",
                 static_folder="static",
                 static_url_path='/home/static')


@home.route("/")
def index():
    return render_template("home/home.html")


@home.route('/about', methods=['GET'])
def about():
    return render_template("home/about.html")

@home.route('/about2', methods=['GET'])
def about2():
    dep_id, dep_name= request.args.get('dep_id'), request.args.get('dep_name')
    return render_template("home/about2.html", dep_id=dep_id, dep_name=dep_name)

@home.route('/about3', methods=['GET'])
def about3():
    doc_id, doc_name= request.args.get('doc_id'), request.args.get('doc_name')
    return render_template("home/about3.html", doc_id=doc_id, doc_name=doc_name)

@home.route('/search', methods=['GET'])
def search():
    return render_template("home/search.html")

@home.app_errorhandler(Exception)
def handle_exception(err):
    return render_template('error/exception.html', err=err)

app/home/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>國立臺中科技大學附設醫院</title>
    <link rel="stylesheet" href="{{ url_for('home.static', filename='css/base.css') }}">
</head>

<body>
    <h1 class="backround">
        <div class="x" style="margin: 570px; padding: -1px;   ">

            <span class="x" style="display: inline-block ; margin-top: -5px; position: relative;top: -75px;">
                <font size="2px" color="white" face="Times New Roman" style="white-space:pre;">身分入口:: </font>
            </span>

            <span class=" x" style="display: inline-block">
                <font size="2 px" color="white" face="Times New Roman"
                    style="white-space:pre;position: relative;top: -37px;left: -70px;">
                    學生&ensp;|&ensp;醫師&ensp;|&ensp;員工&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                </font>
            </span>

            <span class=" x" style="display: inline-block ;">
                <font size="2 px" color="white" face="Times New Roman"
                    style="white-space:pre;position: relative;top: -75px;left: 54px">
                    |&ensp;MyPortal&ensp;|&ensp;疫苗預約&ensp;|&ensp;防疫專區&ensp;|&ensp;English&ensp;|</font>
            </span>



            <span style="position: relative;top: -75px;">

                <img class="imgg" src="{{ url_for('home.static', filename='img/LOGO.png') }}" alt="LOLewss" width="300"
                    height="200 ">

            </span>

            <span style="display:inline-block; margin:-10px;margin-left: 10px;position: relative;top: -130px; ">
                <a href="{{ url_for('home.index') }}">
                    <img class="imgg" src="{{ url_for('home.static', filename='img/img1.png') }}" alt="LOLewss"
                        width="83" height="16 ">
                </a>
                <!-- 關於中科 -->
            </span>

            <td>&emsp;</td>

            <span style="display:inline-block; margin:-10px;margin-left: 10px;position: relative;top: -130px; ">
                <a href="{{ url_for('home.about') }}">
                    <img class="imgg" src="{{ url_for('home.static', filename='img/img2.png') }}" alt="LOLewss"
                        width="83" height="16 ">
                </a>
                <!-- 網路預約 -->
            </span>

            <td>&emsp;</td>

            <span style="display:inline-block; margin:-10px;margin-left: 10px;position: relative;top: -130px; ">
                <a href="{{ url_for('home.search') }}">
                    <img class="imgg" src="{{ url_for('home.static', filename='img/img3.png') }}" alt="LOLewss"
                        width="83" height="16 ">
                </a>
                <!-- 掛號查詢 -->
            </span>

            <hr
                style="display: block;margin-top: -35px;border: 4px solid rgb(230, 230, 230);position: relative;top: -72px;">

            {% block content %}
            {% endblock %}
            {% block body_script %}
            {% endblock %}

        </div>
    </h1>
</body>

</html>

app/home/templates/home/about.html
{% extends "base.html" %}
{% block content %}

<h3 style="margin: 10px;">依科別掛號</h3>
<table id="dep_table" border="0" width="872" align="center">

</table>
{% endblock %}
{% block body_script %}
<script src="{{ url_for('home.static', filename='js/about.js') }}"></script>
{% endblock %}

app/home/templates/home/about2.html
{% extends "base.html" %}
{% block content %}

<h3 style="margin: 10px;">{{ dep_name }} 醫師</h3>
<table id="doc_table" border="0" width="872" align="center">

</table>
{% endblock %}
{% block body_script %}
<script src="{{ url_for('home.static', filename='js/about2.js') }}" , dep_id={{ dep_id }}></script>
{% endblock %}

app/home/templates/home/about3.html
{% extends "base.html" %}
{% block content %}

<h3 style="margin: 10px;">{{doc_name}} 醫師</h3>
<form>
    <table border="1" width="872" align="center">
        <thead>
            <td align="center">
                <h6 style="margin: 10px;">time</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期一</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期二</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期三</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期四</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期五</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期六</h6>
            </td>
            <td align="center">
                <h6 style="margin: 10px;">星期日</h6>
            </td>
        </thead>
        <tbody>
            <tr id="dep_doc_morning">
                <th align="center">
                    <h6 style="margin: 10px;">早上</br>8:30</br>~</br>12:00</h6>
                </th>
                <td align="center" id="mon_morning"></td>
                <td align="center" id="tue_morning"></td>
                <td align="center" id="wed_morning"></td>
                <td align="center" id="thr_morning"></td>
                <td align="center" id="fri_morning"></td>
                <td align="center" id="sat_morning"></td>
                <td align="center" id="sun_morning"></td>
            </tr>
            <tr id="dep_doc_afternoon">
                <th align="center">
                    <h6 style="margin: 10px;">下午</br>13:30</br>~</br>17:00</h6>
                </th>
                <td align="center" id="mon_afternoon"></td>
                <td align="center" id="tue_afternoon"></td>
                <td align="center" id="wed_afternoon"></td>
                <td align="center" id="thr_afternoon"></td>
                <td align="center" id="fri_afternoon"></td>
                <td align="center" id="sat_afternoon"></td>
                <td align="center" id="sun_afternoon"></td>
            </tr>
            <tr id="dep_doc_night">
                <th align="center">
                    <h6 style="margin: 10px;">晚上</br>18:00</br>~</br>21:00</h6>
                </th>
                <td align="center" id="mon_night"></td>
                <td align="center" id="tue_night"></td>
                <td align="center" id="wed_night"></td>
                <td align="center" id="thr_night"></td>
                <td align="center" id="fri_night"></td>
                <td align="center" id="sat_night"></td>
                <td align="center" id="sun_night"></td>
            </tr>
        </tbody>
    </table>
    <table border="0" width="872" align="center">
        <tr>
            <td align="left">
                <h5 style="margin: 10px;">請輸入病歷號及生日</h5>
                <h6 style="margin: 10px;">
                    病歷號：
                    <input type="text" id="app_id"></input>
                    生日：
                    <input type="date" id="app_date"> &emsp;
                    <button type="button" id="app_submit">掛號</button>
                </h6>
            </td>
        </tr>
    </table>
</form>
{% endblock %}
{% block body_script %}
<script src="{{ url_for('home.static', filename='js/about3.js') }}" , doc_id={{ doc_id }}></script>
{% endblock %}

app/home/templates/home/home.html
{% extends "base.html" %}
{% block content %}
<!-- <hr style="display: block;margin-top: -35px;border: 4px solid rgb(230, 230, 230);"> -->
<span style="position:relative;top: 25px;left: 30px;"><img class="imgg"
        src="{{ url_for('.static', filename='img/img4.png') }}" alt="LOLewss" width="872">
</span>

<h5>國立臺中科技大學是一所積極新創、學科齊全、學術實力雄厚、辦學特色鮮明，在國際上具有重要影響力與競爭力的綜合性大學，在多個學術領域具有非常前瞻的科技實力，擁有世界一流的實驗室與師資力量，各種排名均位於全球前列。歡迎大家報考國立臺中科技大學。</h5>
{% endblock %}

app/home/templates/home/search.html
{% extends "base.html" %}
{% block content %}
<h3 style="margin: 10px;">掛號查詢或取消掛號</h3>
<form>
    <table border="0" width="872" align="center">
        <tr>
            <td align="left">
                <h5 style="margin: 10px;">請輸入病歷號及生日</h5>
                <h6 style="margin: 10px;">
                    病歷號：
                    <input type="text" id="search_id"></input>
                    生日：
                    <input type="date" id="search_date"> &emsp;
                    <button type="button" id="search_submit">查詢</button>
                </h6>
            </td>
        </tr>
    </table>
</form>
<br>
<table border="1" width="872" align="center">
    <thead>
        <td align="center">
            日期
        </td>
        <td align="center">
            星期
        </td>
        <td align="center">
            時間
        </td>
        <td align="center">
            科別
        </td>
        <td align="center">
            醫師
        </td>
        <td align="center">
            取消
        </td>
    </thead>
    <tbody id="app_tbody">

    </tbody>
</table>
{% endblock %}
{% block body_script %}
<script src="{{ url_for('home.static', filename='js/search.js') }}" , doc_id={{ doc_id }}></script>
{% endblock %}